### PR TITLE
Covert a Signup image from avif to png

### PR DESCRIPTION
**Pull request by DipeshRaval**
add a signup page frontend and fix error in sign up image

### CODE REVIEW

**Review by JavidSumra — CHANGES_REQUESTED** [review]
Hey @DipeshRaval I think You Can Update the Side Image Please Use Better Placeholders for Input Fields and I think you need to change the line `Don't have an Account?Login` `with already have an Account?Login`

**Comment by DipeshRaval** [comment]
Can You check again signup from UI and also test a submit handle

**Review by JavidSumra — COMMENTED** [review]
All Necessary Changes Completed

**Review by JavidSumra — APPROVED** [review]
Signup Form Successfully Implemented

**Pull request merged**
